### Get all auctions
GET http://localhost:7001/api/auctions

### Get one auctions
GET http://localhost:7001/api/auctions/155225c1-4448-4066-9886-6786536e05ea

### Create a new auction without images
< {%
    let date = new Date();
    date.setDate(date.getDate() + 14);
    let dateString = date.toISOString();
    request.variables.set("dateString", dateString);
%}
POST http://localhost:7001/api/auctions
Content-Type: application/json

{
  "Artist": "Vincent van Gogh",
  "Name": "Sunflowers",
  "Description": "Sunflowers is a series of still-life paintings by Vincent van Gogh. The paintings depict sunflowers in various stages of life and were painted in the late 1880s.",
  "Height": 173.7,
  "Width": 192.1,
  "Medium": "Oil on canvas",
  "Year": 1889,
  "ImageUrl": [
    "https://res.cloudinary.com/dsceyl414/image/upload/v1702814046/ljmlylgfdf6svmvac3pe.jpg",
    "https://res.cloudinary.com/dsceyl414/image/upload/v1702814046/l2wfi4fijgu8agoxqppa.jpg",
    "https://res.cloudinary.com/dsceyl414/image/upload/v1702814046/npi9lg3vvbjhasgojhoj.jpg",
    "https://res.cloudinary.com/dsceyl414/image/upload/v1702814046/h1leto8ktjz1vl1ddxi5.jpg"
  ],
  "ReservePrice": 100000,
  "AuctionEnd": "{{dateString}}"
}

> {%
    let jsonData = response.body;
    client.global.set("createdItemId", jsonData.id);
%}

### Update auctions without images
PATCH http://localhost:7001/api/auctions/{{createdItemId}}
Content-Type: application/json

{
  "Name": "Sunflower"
}

### Delete an auction
DELETE http://localhost:7001/api/auctions/{{createdItemId}}
