apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-svc
spec:
  selector:
    matchLabels:
      app: identity-svc
  template:
    metadata:
      labels:
        app: identity-svc
    spec:
      containers:
        - name: identity-svc
          image: duynguyenbui/identity-svc
          imagePullPolicy: Never
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ConnectionStrings__DefaultConnection
              value: Server=postgres-clusterip:5432;User Id=postgres;Password=postgrespw;Database=identity
            - name: ClientApp
              value: http://app.artelevate.com
---
apiVersion: v1
kind: Service
metadata:
  name: identity-clusterip
spec:
  type: ClusterIP
  selector:
    app: identity-svc
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: identity-lb
spec:
  type: LoadBalancer
  selector:
    app: identity-svc
  ports:
    - port: 80
      targetPort: 80