import { Toaster } from 'sonner';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { AlertDeleteModal } from '@/components/alert-delete-modal';
import { SignalRProvider } from '@/components/signalr-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Art Elevate',
  description: 'Generated by duy nguyen bui',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AlertDeleteModal />
          <Toaster position="bottom-right" />
          <SignalRProvider>{children}</SignalRProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
